version: "3.3"
services:
  otp-bolivia-cochabamba:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes: 
      - ./graphs/Bolivia-Cochabamba:/app/graphs

  otp-bolivia-la-paz:
    build: .
    ports:
      - "8082:8080"
      - "8083:8081"
    volumes: 
      - ./graphs/Bolivia-LaPaz:/app/graphs
      
  otp-colombia-duitama:
    build: .
    ports:
      - "8084:8080"
      - "8085:8081"
    volumes: 
      - ./graphs/Colombia-Duitama:/app/graphs

  otp-colombia-yopal:
    build: .
    ports:
      - "8086:8080"
      - "8087:8081"
    volumes: 
      - ./graphs/Colombia-Yopal:/app/graphs